### ISSUE TITLE
No-ip Configuration...

### ISSUE THREAD

**Issue by Cankepou** [TheQuib/dji-obs-stream#1]
Bonjour,
J'essaie de trouver comment lier votre réalisation avec no-ip (DUC) pour windows  (11).
Lors des essais il ne m'est pas possible d'atteindre la page NGINX accessible, par l'IP de la machine hôte.

**Comment by Cankepou** [comment]
Oups.. J'ai trouvé comment lier votre app avec noip, il suffisait de mettre le dossier dans la racine web de windows (C:\inetpub\wwwroot), et d'ouvrir les ports 1935 et 80 dans le routeur, comme dans la documentation.

**Comment by TheQuib** [comment]
All good. Thanks for the update :)
