### ISSUE TITLE
missing server file

### ISSUE THREAD

**Issue by sebk95** [TheQuib/dji-obs-stream#2]
Missing file for configuration /live and streamkey.
DJI App refuse all connection now but ngix is up and Firewall port is open

**Comment by TheQuib** [comment]
Config for the `/live` directory can be found in `/Windows/conf/nginx.conf`...


In this block:

```conf
rtmp {
    server {
        listen 1935;
        application live {
            live on;
            interleave on;
            record off;

        }
    }
}
```

Streamkey is defined by streaming to a directory under `/live` (such as `/live/streamKey1`. Point your OBS media source to that directory (including the key) and it should work.
